apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: applications.argoproj.io
spec:
  group: argoproj.io
  names:
    kind: Application
    listKind: ApplicationList
    plural: applications
    singular: application
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                project:
                  type: string
                source:
                  type: object
                  properties:
                    repoURL:
                      type: string
                    targetRevision:
                      type: string
                    path:
                      type: string
                destination:
                  type: object
                  properties:
                    server:
                      type: string
                    namespace:
                      type: string
                syncPolicy:
                  type: object
                  properties:
                    automated:
                      type: object
                      properties:
                        prune:
                          type: boolean
                        selfHeal:
                          type: boolean